### PR TITLE
fix sever crash (now work on server)

### PR DESCRIPTION
**Pull request by quentfr21**
re-work guihandler
fix recipechecker load on invalid side

### CODE REVIEW

**Comment by LepkoQQ** [comment]
Yeah, I know I have to fix this, however I have another way in mind. Keeping open until I fix the crash.

**Comment by 4rz0** [comment]
Isn't this already fixed in the 1.7.x version?

**Comment by LepkoQQ** [comment]
Well master is on 1.7 now and your PR is for master, so no?

**Comment by quentfr21** [comment]
my PR is for 1.7

i make change from your master branch fork this morning
i know it's probably a bad way to fix it but now i can run it on my serv with mc 1.7.2 without problem
forge 1.7.2.10.12.2.1147

**Comment by LepkoQQ** [comment]
@quentffr21 sorry my reply was to 4rzo.
there is nothing wrong with your way, i just wanted to do it another way, anyway fixed now, closing (0e2108ca2cff2102b168a867d50c0fb34bd35f58)

**Comment by 4rz0** [comment]
Jup, looks like I was just being confused.
Thanks for the fix!

**Pull request closed without merging**
